DROP DATABASE IF EXISTS uno;

CREATE DATABASE uno;

USE uno;

CREATE TABLE user(
userID INT UNSIGNED AUTO_INCREMENT,
username VARCHAR(25) UNIQUE NOT NULL,
password VARCHAR(256) NOT NULL,
wins INT UNSIGNED,
CONSTRAINT user_pk PRIMARY KEY (userID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE card(
cardID SMALLINT UNSIGNED,
color VARCHAR(8),
value VARCHAR(10),
image VARCHAR(40),
CONSTRAINT card_pk PRIMARY KEY (cardID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE game(
gameID INT UNSIGNED AUTO_INCREMENT,
player1ID INT UNSIGNED,
player2ID INT UNSIGNED,
turn TINYINT UNSIGNED,
winner INT UNSIGNED,
CONSTRAINT game_pk PRIMARY KEY (gameID),
CONSTRAINT game_player1ID_fk FOREIGN KEY (player1ID) REFERENCES user(userID),
CONSTRAINT game_player2ID_fk FOREIGN KEY (player2ID) REFERENCES user(userID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE userCard(
userID INT UNSIGNED,
cardID SMALLINT UNSIGNED,
gameID INT UNSIGNED,
CONSTRAINT userCard_pk PRIMARY KEY (userID, cardID, gameID),
CONSTRAINT userCard_userID_fk FOREIGN KEY (userID) REFERENCES user(userID),
CONSTRAINT userCard_cardID_fk FOREIGN KEY (cardID) REFERENCES card(cardID),
CONSTRAINT userCard_gameID_fk FOREIGN KEY (gameID) REFERENCES game(gameID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE gameCard(
gameID INT UNSIGNED,
turnNumber INT UNSIGNED,
cardID SMALLINT UNSIGNED,
CONSTRAINT gameCard_pk PRIMARY KEY (gameID, turnNumber),
CONSTRAINT gameCard_gameID_fk FOREIGN KEY (gameID) REFERENCES game(gameID),
CONSTRAINT gameCard_cardID_fk FOREIGN KEY (cardID) REFERENCES card(cardID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE lobbyChat(
messageID INT UNSIGNED AUTO_INCREMENT,
sent DATETIME DEFAULT CURRENT_TIMESTAMP,
message TEXT(500),
username VARCHAR(25) NOT NULL,
CONSTRAINT lobbyChat_pk PRIMARY KEY (messageID),
CONSTRAINT lobbyChat_username_fk FOREIGN KEY (username) REFERENCES user(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE gameChat(
messageID INT UNSIGNED AUTO_INCREMENT,
sent DATETIME DEFAULT CURRENT_TIMESTAMP,
message TEXT(500),
username VARCHAR(25) NOT NULL,
gameID INT UNSIGNED,
CONSTRAINT gameChat_pk PRIMARY KEY (messageID),
CONSTRAINT gameChat_username_fk FOREIGN KEY (username) REFERENCES user(username),
CONSTRAINT gameChat_gameID_fk FOREIGN KEY (gameID) REFERENCES game(gameID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
